<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="DTOs\" />
    <Folder Include="Commands\" />
    <Folder Include="Interfaces\Service\" />
    <Folder Include="Queries\" />
    <Folder Include="Services\" />
    <Folder Include="Validators\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Diploma.Domain\A Diploma.Domain.csproj" />
  </ItemGroup>

</Project>
